package com.aptana.editor.dtd.parsing;

import java.util.ArrayList;
import com.aptana.editor.dtd.parsing.ast.*;
import beaver.*;
import com.aptana.parsing.IParser;
import com.aptana.parsing.ast.IParseNode;
import com.aptana.parsing.IParseState;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "DTD.grammar".
 */
@SuppressWarnings({ "unchecked", "rawtypes" })
public class DTDParser extends Parser implements IParser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9oTbdcSJMKOnt$ttBbKAbb6CoCJeccHTOpbcasZCMQ65jhJQYdHXfOXKob48IrK$rWYXK8" +
		"YYZQjoBupjXQXgMYRokFtlkVXS#RCdN77EP$l#tkVvtctyvxdtFS2AC4hY44LLCLfE1rdu3" +
		"xSZxDmDfgWEIw0Ws34w5NeWukGB9CnB6ByfOZUst4rpa4tN8a4EOhpS1sknmsu4JVXPjo2d" +
		"dW2rJ44L#01X50DPuhuFJY$ZCTlvoCD7H5lrvyacz4TFN0jRiLjI4S6CcKzwgCr6g0zQk9o" +
		"PA4JOd4kQg0MBiObk1INeIcQeH5IK1UrqG4jq1AjT3TCsSwMOLkcuYcCHMCauaAp6vOwQ6D" +
		"rDEzdy31lOyMXdjNEoCC0T66PWroqnLtepRKaucxqmqDuL7RA3lOOYWbuKhRBDen2GmoIJU" +
		"YFUsMZR91riXO5iWPTaOrhS0VkH2$SWmVH5yzX80RZCJoEfr68uHY1aR88Z#1P5E1vZCSOZ" +
		"CCBU17cUfbhTvyhcNkHmXMtvNErrsTFAoSQOYwOVEXQJZoojnwVp#7UDUA#WplMc7kLnBrm" +
		"Txi9iyEyDPCTrPaRDTZ6xt7AUFnsXbrvKDSVu2xdS8zpkSjk1WQOZIOVgx3cUZenO#eo0rt" +
		"BBKqsnB55lDhkQ6NB46ztD4Ttn8nlj2Rl0FCfLhrngWxpo9JfrFWJQp4QjZrCdqJcjcFh3Q" +
		"dPrDgy0thN8fdqk#yWbLdkC9fWOo7cN9Wv763UksqTIvWHOzSHNem34mljwsS4o3Vroi2hD" +
		"Ub32jGUepfTTQvg0Xb8lY2laMz9Tusj82krFeYyhlN9gaDzSnRwx94#UwhgDDKPgdDKvwds" +
		"9wl9EhAU32ORo4QocMmX2xJj8i$uSIJMEwVwD$bzqS9hAzbE5gkzH7KLMQhrPHNqBoBpoLw" +
		"rzwbkKzrDbclzRRA6P96rwlkQJ2BxrPwbUa3r43b8VY4xI35vbHpM#17LNQG7sUDT7vDjDI" +
		"cAPYyYF5luP6quzawJqL6CbUsffvtYUdhvxBwg$LG7L6Ai8Qg57byIcNGgQujYlYaHV1EYx" +
		"3kgCdFnTHJx#i$sr6T6CT$2SiOjyRMRw8hyB$zAYVmZVyjVygVy8KVaiBmXqpJwE$cD$4gA" +
		"uRbagosts9BVWNmb2#LzMI3loNoP9tFbNNb7viXicSKOVxzaEVcSV4a#GuHB#9N88Jbewp$" +
		"8IbaX$BsJR$WLV2Uhv5FvH3wMPR9KFf8FPOaibW#q7xzCUSlMPf8tPOPCbmFoi#pN#4$aHx" +
		"BBMaKdvfkg#ZtPH$RwrhE7xDRw5FcFqfDdTe3mA#2vaCPwSmyjog4LOagHpBCdcPfkJx80J" +
		"mEN5FeC7HXlGtK9yVnt2TkpACWppU6v6oGnLbCj3a$Y074ybBOpQ1ydinGEJ#GOdjj1ujX$" +
		"04rfPr6pQ7TccvmAwA9qP5lphw6PrUDKRETodbm#MnxdocFTdCVvRDDIQSUO#SVKxHY1azZ" +
		"q");

	private DTDScanner _scanner;
	
	/*
	 * (non-Javadoc)
	 * @see com.aptana.parsing.IParser#parse(com.aptana.parsing.IParseState)
	 */
	@Override
	public synchronized IParseNode parse(IParseState parseState) throws java.lang.Exception
	{
		// grab source
		char[] characters = parseState.getSource();

		// make sure we have some source
		String source = (characters != null) ? new String(characters) : "";

		// send source to the scanner
		this._scanner.setSource(source);

		// parse
		IParseNode result = (IParseNode) parse(this._scanner);
		
		// save reference to result
		parseState.setParseResult(result);
		
		return result;
	}

	public DTDParser() {
		super(PARSING_TABLES);


		this._scanner = new DTDScanner();
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		switch(rule_num) {
			case 0: // DTD = Declarations.d
			{
					final Symbol _symbol_d = _symbols[offset + 1];
					final ArrayList _list_d = (ArrayList) _symbol_d.value;
					final beaver.Symbol[] d = _list_d == null ? new beaver.Symbol[0] : (beaver.Symbol[]) _list_d.toArray(new beaver.Symbol[_list_d.size()]);
					
		return new DTDParseRootNode(d);
			}
			case 1: // DTD = 
			{
					
		return new DTDParseRootNode();
			}
			case 2: // Declarations = Declarations Declaration
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2]); return _symbols[offset + 1];
			}
			case 3: // Declarations = Declaration
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1]); return new Symbol(lst);
			}
			case 11: // MarkupDecl = PI.p
			{
					final Symbol _symbol_p = _symbols[offset + 1];
					final String p = (String) _symbol_p.value;
					
		String content = p.substring(2, p.length() - 2);
		
		return new DTDProcessingInstructionNode(content);
			}
			case 13: // ElementDecl = ELEMENT NAME.n EMPTY GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDElementDeclarationNode(n);
			}
			case 14: // ElementDecl = ELEMENT NAME.n ANY GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDElementDeclarationNode(n);
			}
			case 15: // ElementDecl = ELEMENT NAME.n Mixed GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDElementDeclarationNode(n);
			}
			case 16: // ElementDecl = ELEMENT NAME.n Children GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDElementDeclarationNode(n);
			}
			case 17: // AttlistDecl = ATTLIST NAME.n GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDAttributeListDeclarationNode(n);
			}
			case 18: // AttlistDecl = ATTLIST NAME.n AttDefs GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDAttributeListDeclarationNode(n);
			}
			case 19: // AttDefs = AttDefs AttDef
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2]); return _symbols[offset + 1];
			}
			case 20: // AttDefs = AttDef
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1]); return new Symbol(lst);
			}
			case 23: // NotationDecl = NOTATION NAME.n ExternalID GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDNotationDeclarationNode(n);
			}
			case 24: // NotationDecl = NOTATION NAME.n PublicID GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDNotationDeclarationNode(n);
			}
			case 26: // GEDecl = ENTITY NAME.n STRING GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDGEntityDeclarationNode(n);
			}
			case 27: // GEDecl = ENTITY NAME.n ExternalID GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDGEntityDeclarationNode(n);
			}
			case 28: // GEDecl = ENTITY NAME.n ExternalID NDataDecl GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 2];
					final String n = (String) _symbol_n.value;
					
		return new DTDGEntityDeclarationNode(n);
			}
			case 29: // PEDecl = ENTITY PERCENT NAME.n STRING.s GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 3];
					final String n = (String) _symbol_n.value;
					final Symbol _symbol_s = _symbols[offset + 4];
					final String s = (String) _symbol_s.value;
					
		String value = s.substring(1, s.length() - 1);
		this._scanner.register(n, value);
		
		return new DTDPEntityDeclarationNode(n);
			}
			case 30: // PEDecl = ENTITY PERCENT NAME.n ExternalID GREATER_THAN
			{
					final Symbol _symbol_n = _symbols[offset + 3];
					final String n = (String) _symbol_n.value;
					
		return new DTDPEntityDeclarationNode(n);
			}
			case 88: // NmTokens = NmTokens NMTOKEN
			{
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2]); return _symbols[offset + 1];
			}
			case 89: // NmTokens = NMTOKEN
			{
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1]); return new Symbol(lst);
			}
			case 4: // Declaration = MarkupDecl
			case 5: // Declaration = PE_REF
			case 6: // Declaration = ConditionalSect
			case 7: // MarkupDecl = ElementDecl
			case 8: // MarkupDecl = AttlistDecl
			case 9: // MarkupDecl = EntityDecl
			case 10: // MarkupDecl = NotationDecl
			case 12: // MarkupDecl = COMMENT
			case 21: // EntityDecl = GEDecl
			case 22: // EntityDecl = PEDecl
			case 39: // Children = Choice
			case 43: // Children = Seq
			case 47: // AttType = StringType
			case 48: // AttType = TokenizedType
			case 49: // AttType = EnumeratedType
			case 50: // DefaultDecl = REQUIRED
			case 51: // DefaultDecl = IMPLIED
			case 52: // DefaultDecl = STRING
			case 61: // StringType = CDATA_TYPE
			case 62: // TokenizedType = ID_TYPE
			case 63: // TokenizedType = IDREF_TYPE
			case 64: // TokenizedType = IDREFS_TYPE
			case 65: // TokenizedType = ENTITY_TYPE
			case 66: // TokenizedType = ENTITIES_TYPE
			case 67: // TokenizedType = NMTOKEN_TYPE
			case 68: // TokenizedType = NMTOKENS_TYPE
			case 69: // EnumeratedType = NotationType
			case 70: // EnumeratedType = Enumeration
			case 72: // Cp = NAME
			case 76: // Cp = Choice
			case 80: // Cp = Seq
			case 90: // ConditionalSect = IncludeSect
			case 91: // ConditionalSect = IgnoreSect
			{
				return _symbols[offset + 1];
			}
			case 31: // ExternalID = SYSTEM SYSTEM_LITERAL
			case 33: // PublicID = PUBLIC STRING
			case 38: // Names = PIPE NAME
			case 40: // Children = Choice QUESTION
			case 41: // Children = Choice STAR
			case 42: // Children = Choice PLUS
			case 44: // Children = Seq QUESTION
			case 45: // Children = Seq STAR
			case 46: // Children = Seq PLUS
			case 53: // DefaultDecl = FIXED STRING
			case 56: // ChoiceCps = PIPE Cp
			case 60: // SeqCps = COMMA Cp
			case 71: // NDataDecl = NDATA NAME
			case 73: // Cp = NAME QUESTION
			case 74: // Cp = NAME STAR
			case 75: // Cp = NAME PLUS
			case 77: // Cp = Choice QUESTION
			case 78: // Cp = Choice STAR
			case 79: // Cp = Choice PLUS
			case 81: // Cp = Seq QUESTION
			case 82: // Cp = Seq STAR
			case 83: // Cp = Seq PLUS
			{
				return _symbols[offset + 2];
			}
			case 25: // AttDef = NAME AttType DefaultDecl
			case 32: // ExternalID = PUBLIC STRING SYSTEM_LITERAL
			case 34: // Mixed = LPAREN PCDATA RPAREN_STAR
			case 36: // Mixed = LPAREN PCDATA RPAREN
			case 37: // Names = Names PIPE NAME
			case 55: // ChoiceCps = ChoiceCps PIPE Cp
			case 57: // Seq = LPAREN Cp RPAREN
			case 59: // SeqCps = SeqCps COMMA Cp
			case 86: // Enumeration = LPAREN NMTOKEN RPAREN
			{
				return _symbols[offset + 3];
			}
			case 35: // Mixed = LPAREN PCDATA Names RPAREN_STAR
			case 54: // Choice = LPAREN Cp ChoiceCps RPAREN
			case 58: // Seq = LPAREN Cp SeqCps RPAREN
			case 84: // NotationType = NOTATION_TYPE LPAREN NAME RPAREN
			case 87: // Enumeration = LPAREN NMTOKEN NmTokens RPAREN
			{
				return _symbols[offset + 4];
			}
			case 85: // NotationType = NOTATION_TYPE LPAREN NAME Names RPAREN
			case 92: // IncludeSect = SECTION_START INCLUDE LBRACKET Declaration SECTION_END
			case 93: // IgnoreSect = SECTION_START IGNORE LBRACKET Declaration SECTION_END
			{
				return _symbols[offset + 5];
			}
			default:
				throw new IllegalArgumentException("unknown production #" + rule_num);
		}
	}
}
